In [27]:
## Assignment for MCA
## 1.2

import numpy as np

In [37]:
# Question (a)
# Random 3x2 matrix with the mean of each column subtracted
data = np.random.rand(3,2)
meand = d.mean(axis=0)
d = data - meand
#data = d - np.mean(d)

In [38]:
# U = left singular vectors
# V = Right singular vectors
# L = Singular value matrix
U, L, V = np.linalg.svd(d, full_matrices = True)

In [39]:
U.shape, L.shape, V.shape

((3, 3), (2,), (2, 2))

In [40]:
## Reconstruction by multiplying U*L

#np.allclose(d, np.dot(U[:, :2] * L, V))
smat = np.zeros((3, 2))
smat[:2, :2] = np.diag(L)
#np.allclose(d, np.dot(U, np.dot(smat, V)))


In [41]:
smat

array([[1.08661798, 0.        ],
       [0.        , 0.4172579 ],
       [0.        , 0.        ]])

In [42]:
d_rec1 = np.dot(U, smat)
d_rec1, d

(array([[-0.44921916, -0.14369492],
        [-0.47874156, -0.3064682 ],
        [-0.8658795 ,  0.2439942 ]]), array([[-0.42071571, -0.21317687],
        [-0.55604419, -0.11803007],
        [-0.44507595, -0.78178506]]))

In [43]:
#data_rec = np.dot(d_rec1, V)

In [44]:
#data_rec, d

In [45]:
# Question (b)

# 3X3 covariance matrix

d_dt = np.dot(d, np.transpose(d))

# 2x2 covariance matrix

dt_d = np.dot(np.transpose(d), d)

d_dt, dt_d


(array([[0.22244608, 0.2590978 , 0.35390894],
        [0.2590978 , 0.32311623, 0.33975604],
        [0.35390894, 0.33975604, 0.80928048]]),
 array([[0.68427944, 0.50327052],
        [0.50327052, 0.67056336]]))

In [46]:
# Eigenvectors and eigenvalues of covariance matrix 3x3

w1, v1 = np.linalg.eig(d_dt)

In [47]:
w1.shape, v1.shape

((3,), (3, 3))

In [48]:
#w1_new = np.zeros((3, 3))
#w1_new[:3, :3] = np.diag(w1)

In [49]:
#w1_new.shape

In [50]:
#w1_new

In [51]:
# Reconstruct from covariance matrix 3x3
#d_dt_rec1 = np.dot(v1, w1_new)
d_rec2 = np.dot(v1, d)
d_rec2, d_rec1, d

(array([[ 0.79589753,  0.45684856],
        [ 0.22524797,  0.60720496],
        [-0.00948253, -0.30521285]]), array([[-0.44921916, -0.14369492],
        [-0.47874156, -0.3064682 ],
        [-0.8658795 ,  0.2439942 ]]), array([[-0.42071571, -0.21317687],
        [-0.55604419, -0.11803007],
        [-0.44507595, -0.78178506]]))

In [52]:
#Eigenvectors and eigenvalues of covariance matrix 2x2
 
w2, v2 = np.linalg.eig(dt_d)
w2.shape, v2.shape
#w2_new = np.zeros((2, 2))
#w2_new[:2, :2] = np.diag(w2)
#w2_new.shape, w2_new

((2,), (2, 2))

In [53]:
# Reconstruct from covariance matrci 2x2

#dt_d_rec1 = np.dot(v2, w2_new)
d_rec3 = np.dot(d, v2)
d_rec3, d_rec2, d_rec1, d

(array([[-0.44921916,  0.14369492],
        [-0.47874156,  0.3064682 ],
        [-0.8658795 , -0.2439942 ]]), array([[ 0.79589753,  0.45684856],
        [ 0.22524797,  0.60720496],
        [-0.00948253, -0.30521285]]), array([[-0.44921916, -0.14369492],
        [-0.47874156, -0.3064682 ],
        [-0.8658795 ,  0.2439942 ]]), array([[-0.42071571, -0.21317687],
        [-0.55604419, -0.11803007],
        [-0.44507595, -0.78178506]]))